/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V4beta1QueryCollectionRequest QueryCollectionRequest is a request to perform a search using a pipeline.
type V4beta1QueryCollectionRequest struct {
	Pipeline *V4beta1QueryCollectionRequestPipeline `json:"pipeline,omitempty"`
	// The initial values for the variables the pipeline operates on and transforms throughout its steps.  A typical variable is `q` which is the query the user entered, for example:  ```json { \"q\": \"search terms\" } ```
	Variables map[string]interface{} `json:"variables"`
	Tracking  *V2Tracking            `json:"tracking,omitempty"`
}

// NewV4beta1QueryCollectionRequest instantiates a new V4beta1QueryCollectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4beta1QueryCollectionRequest(variables map[string]interface{}) *V4beta1QueryCollectionRequest {
	this := V4beta1QueryCollectionRequest{}
	this.Variables = variables
	return &this
}

// NewV4beta1QueryCollectionRequestWithDefaults instantiates a new V4beta1QueryCollectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4beta1QueryCollectionRequestWithDefaults() *V4beta1QueryCollectionRequest {
	this := V4beta1QueryCollectionRequest{}
	return &this
}

// GetPipeline returns the Pipeline field value if set, zero value otherwise.
func (o *V4beta1QueryCollectionRequest) GetPipeline() V4beta1QueryCollectionRequestPipeline {
	if o == nil || o.Pipeline == nil {
		var ret V4beta1QueryCollectionRequestPipeline
		return ret
	}
	return *o.Pipeline
}

// GetPipelineOk returns a tuple with the Pipeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1QueryCollectionRequest) GetPipelineOk() (*V4beta1QueryCollectionRequestPipeline, bool) {
	if o == nil || o.Pipeline == nil {
		return nil, false
	}
	return o.Pipeline, true
}

// HasPipeline returns a boolean if a field has been set.
func (o *V4beta1QueryCollectionRequest) HasPipeline() bool {
	if o != nil && o.Pipeline != nil {
		return true
	}

	return false
}

// SetPipeline gets a reference to the given V4beta1QueryCollectionRequestPipeline and assigns it to the Pipeline field.
func (o *V4beta1QueryCollectionRequest) SetPipeline(v V4beta1QueryCollectionRequestPipeline) {
	o.Pipeline = &v
}

// GetVariables returns the Variables field value
func (o *V4beta1QueryCollectionRequest) GetVariables() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value
// and a boolean to check if the value has been set.
func (o *V4beta1QueryCollectionRequest) GetVariablesOk() (*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Variables, true
}

// SetVariables sets field value
func (o *V4beta1QueryCollectionRequest) SetVariables(v map[string]interface{}) {
	o.Variables = v
}

// GetTracking returns the Tracking field value if set, zero value otherwise.
func (o *V4beta1QueryCollectionRequest) GetTracking() V2Tracking {
	if o == nil || o.Tracking == nil {
		var ret V2Tracking
		return ret
	}
	return *o.Tracking
}

// GetTrackingOk returns a tuple with the Tracking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1QueryCollectionRequest) GetTrackingOk() (*V2Tracking, bool) {
	if o == nil || o.Tracking == nil {
		return nil, false
	}
	return o.Tracking, true
}

// HasTracking returns a boolean if a field has been set.
func (o *V4beta1QueryCollectionRequest) HasTracking() bool {
	if o != nil && o.Tracking != nil {
		return true
	}

	return false
}

// SetTracking gets a reference to the given V2Tracking and assigns it to the Tracking field.
func (o *V4beta1QueryCollectionRequest) SetTracking(v V2Tracking) {
	o.Tracking = &v
}

func (o V4beta1QueryCollectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pipeline != nil {
		toSerialize["pipeline"] = o.Pipeline
	}
	if true {
		toSerialize["variables"] = o.Variables
	}
	if o.Tracking != nil {
		toSerialize["tracking"] = o.Tracking
	}
	return json.Marshal(toSerialize)
}

type NullableV4beta1QueryCollectionRequest struct {
	value *V4beta1QueryCollectionRequest
	isSet bool
}

func (v NullableV4beta1QueryCollectionRequest) Get() *V4beta1QueryCollectionRequest {
	return v.value
}

func (v *NullableV4beta1QueryCollectionRequest) Set(val *V4beta1QueryCollectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV4beta1QueryCollectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV4beta1QueryCollectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4beta1QueryCollectionRequest(val *V4beta1QueryCollectionRequest) *NullableV4beta1QueryCollectionRequest {
	return &NullableV4beta1QueryCollectionRequest{value: val, isSet: true}
}

func (v NullableV4beta1QueryCollectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4beta1QueryCollectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
