/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Sajariv4beta1DeleteRecordRequest struct for Sajariv4beta1DeleteRecordRequest
type Sajariv4beta1DeleteRecordRequest struct {
	Key Sajariv4beta1Key `json:"key"`
}

// NewSajariv4beta1DeleteRecordRequest instantiates a new Sajariv4beta1DeleteRecordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSajariv4beta1DeleteRecordRequest(key Sajariv4beta1Key) *Sajariv4beta1DeleteRecordRequest {
	this := Sajariv4beta1DeleteRecordRequest{}
	this.Key = key
	return &this
}

// NewSajariv4beta1DeleteRecordRequestWithDefaults instantiates a new Sajariv4beta1DeleteRecordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSajariv4beta1DeleteRecordRequestWithDefaults() *Sajariv4beta1DeleteRecordRequest {
	this := Sajariv4beta1DeleteRecordRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *Sajariv4beta1DeleteRecordRequest) GetKey() Sajariv4beta1Key {
	if o == nil {
		var ret Sajariv4beta1Key
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *Sajariv4beta1DeleteRecordRequest) GetKeyOk() (*Sajariv4beta1Key, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *Sajariv4beta1DeleteRecordRequest) SetKey(v Sajariv4beta1Key) {
	o.Key = v
}

func (o Sajariv4beta1DeleteRecordRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["key"] = o.Key
	}
	return json.Marshal(toSerialize)
}

type NullableSajariv4beta1DeleteRecordRequest struct {
	value *Sajariv4beta1DeleteRecordRequest
	isSet bool
}

func (v NullableSajariv4beta1DeleteRecordRequest) Get() *Sajariv4beta1DeleteRecordRequest {
	return v.value
}

func (v *NullableSajariv4beta1DeleteRecordRequest) Set(val *Sajariv4beta1DeleteRecordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSajariv4beta1DeleteRecordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSajariv4beta1DeleteRecordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSajariv4beta1DeleteRecordRequest(val *Sajariv4beta1DeleteRecordRequest) *NullableSajariv4beta1DeleteRecordRequest {
	return &NullableSajariv4beta1DeleteRecordRequest{value: val, isSet: true}
}

func (v NullableSajariv4beta1DeleteRecordRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSajariv4beta1DeleteRecordRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
