/*
 * Search.io API
 *
 * Search.io is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4
 * Contact: support@search.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PromotionRangeBoost struct for PromotionRangeBoost
type PromotionRangeBoost struct {
	// Number that determines the size of the boost that is applied to matching records. Must be greater than or equal to 0 and less than or equal to 1.
	Boost *float32 `json:"boost,omitempty"`
	// The end value to apply 1 boost to.
	End *float32 `json:"end,omitempty"`
	// The field to apply the boost to.
	Field *string `json:"field,omitempty"`
	// The boost given to null/empty values. Must be greater than or equal to 0 and less than or equal to 1. The default value is 0.
	NullBoost *float32 `json:"null_boost,omitempty"`
	// The start value to apply 0 boost to.
	Start *float32 `json:"start,omitempty"`
}

// NewPromotionRangeBoost instantiates a new PromotionRangeBoost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotionRangeBoost() *PromotionRangeBoost {
	this := PromotionRangeBoost{}
	return &this
}

// NewPromotionRangeBoostWithDefaults instantiates a new PromotionRangeBoost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotionRangeBoostWithDefaults() *PromotionRangeBoost {
	this := PromotionRangeBoost{}
	return &this
}

// GetBoost returns the Boost field value if set, zero value otherwise.
func (o *PromotionRangeBoost) GetBoost() float32 {
	if o == nil || o.Boost == nil {
		var ret float32
		return ret
	}
	return *o.Boost
}

// GetBoostOk returns a tuple with the Boost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionRangeBoost) GetBoostOk() (*float32, bool) {
	if o == nil || o.Boost == nil {
		return nil, false
	}
	return o.Boost, true
}

// HasBoost returns a boolean if a field has been set.
func (o *PromotionRangeBoost) HasBoost() bool {
	if o != nil && o.Boost != nil {
		return true
	}

	return false
}

// SetBoost gets a reference to the given float32 and assigns it to the Boost field.
func (o *PromotionRangeBoost) SetBoost(v float32) {
	o.Boost = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *PromotionRangeBoost) GetEnd() float32 {
	if o == nil || o.End == nil {
		var ret float32
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionRangeBoost) GetEndOk() (*float32, bool) {
	if o == nil || o.End == nil {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *PromotionRangeBoost) HasEnd() bool {
	if o != nil && o.End != nil {
		return true
	}

	return false
}

// SetEnd gets a reference to the given float32 and assigns it to the End field.
func (o *PromotionRangeBoost) SetEnd(v float32) {
	o.End = &v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *PromotionRangeBoost) GetField() string {
	if o == nil || o.Field == nil {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionRangeBoost) GetFieldOk() (*string, bool) {
	if o == nil || o.Field == nil {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *PromotionRangeBoost) HasField() bool {
	if o != nil && o.Field != nil {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *PromotionRangeBoost) SetField(v string) {
	o.Field = &v
}

// GetNullBoost returns the NullBoost field value if set, zero value otherwise.
func (o *PromotionRangeBoost) GetNullBoost() float32 {
	if o == nil || o.NullBoost == nil {
		var ret float32
		return ret
	}
	return *o.NullBoost
}

// GetNullBoostOk returns a tuple with the NullBoost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionRangeBoost) GetNullBoostOk() (*float32, bool) {
	if o == nil || o.NullBoost == nil {
		return nil, false
	}
	return o.NullBoost, true
}

// HasNullBoost returns a boolean if a field has been set.
func (o *PromotionRangeBoost) HasNullBoost() bool {
	if o != nil && o.NullBoost != nil {
		return true
	}

	return false
}

// SetNullBoost gets a reference to the given float32 and assigns it to the NullBoost field.
func (o *PromotionRangeBoost) SetNullBoost(v float32) {
	o.NullBoost = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *PromotionRangeBoost) GetStart() float32 {
	if o == nil || o.Start == nil {
		var ret float32
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionRangeBoost) GetStartOk() (*float32, bool) {
	if o == nil || o.Start == nil {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *PromotionRangeBoost) HasStart() bool {
	if o != nil && o.Start != nil {
		return true
	}

	return false
}

// SetStart gets a reference to the given float32 and assigns it to the Start field.
func (o *PromotionRangeBoost) SetStart(v float32) {
	o.Start = &v
}

func (o PromotionRangeBoost) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Boost != nil {
		toSerialize["boost"] = o.Boost
	}
	if o.End != nil {
		toSerialize["end"] = o.End
	}
	if o.Field != nil {
		toSerialize["field"] = o.Field
	}
	if o.NullBoost != nil {
		toSerialize["null_boost"] = o.NullBoost
	}
	if o.Start != nil {
		toSerialize["start"] = o.Start
	}
	return json.Marshal(toSerialize)
}

type NullablePromotionRangeBoost struct {
	value *PromotionRangeBoost
	isSet bool
}

func (v NullablePromotionRangeBoost) Get() *PromotionRangeBoost {
	return v.value
}

func (v *NullablePromotionRangeBoost) Set(val *PromotionRangeBoost) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotionRangeBoost) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotionRangeBoost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotionRangeBoost(val *PromotionRangeBoost) *NullablePromotionRangeBoost {
	return &NullablePromotionRangeBoost{value: val, isSet: true}
}

func (v NullablePromotionRangeBoost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotionRangeBoost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
