/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V4beta1BatchPutRecordsResponse struct for V4beta1BatchPutRecordsResponse
type V4beta1BatchPutRecordsResponse struct {
	// A list of keys of the records that were inserted.  If a record was inserted, keys contains an entry containing the index of the inserted record from `records` and the key. You can use the key if you need to retrieve or delete the record.  If a record was updated, keys contains no such entry for the updated record.
	Keys *[]V4beta1BatchPutRecordsResponseKey `json:"keys,omitempty"`
	// A list of modified variables returned by the pipeline after it has finished processing each record.
	Variables *[]BatchPutRecordsResponseVariables `json:"variables,omitempty"`
	// Errors that occurred.
	Errors *[]V4beta1BatchPutRecordsResponseError `json:"errors,omitempty"`
}

// NewV4beta1BatchPutRecordsResponse instantiates a new V4beta1BatchPutRecordsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4beta1BatchPutRecordsResponse() *V4beta1BatchPutRecordsResponse {
	this := V4beta1BatchPutRecordsResponse{}
	return &this
}

// NewV4beta1BatchPutRecordsResponseWithDefaults instantiates a new V4beta1BatchPutRecordsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4beta1BatchPutRecordsResponseWithDefaults() *V4beta1BatchPutRecordsResponse {
	this := V4beta1BatchPutRecordsResponse{}
	return &this
}

// GetKeys returns the Keys field value if set, zero value otherwise.
func (o *V4beta1BatchPutRecordsResponse) GetKeys() []V4beta1BatchPutRecordsResponseKey {
	if o == nil || o.Keys == nil {
		var ret []V4beta1BatchPutRecordsResponseKey
		return ret
	}
	return *o.Keys
}

// GetKeysOk returns a tuple with the Keys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1BatchPutRecordsResponse) GetKeysOk() (*[]V4beta1BatchPutRecordsResponseKey, bool) {
	if o == nil || o.Keys == nil {
		return nil, false
	}
	return o.Keys, true
}

// HasKeys returns a boolean if a field has been set.
func (o *V4beta1BatchPutRecordsResponse) HasKeys() bool {
	if o != nil && o.Keys != nil {
		return true
	}

	return false
}

// SetKeys gets a reference to the given []V4beta1BatchPutRecordsResponseKey and assigns it to the Keys field.
func (o *V4beta1BatchPutRecordsResponse) SetKeys(v []V4beta1BatchPutRecordsResponseKey) {
	o.Keys = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *V4beta1BatchPutRecordsResponse) GetVariables() []BatchPutRecordsResponseVariables {
	if o == nil || o.Variables == nil {
		var ret []BatchPutRecordsResponseVariables
		return ret
	}
	return *o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1BatchPutRecordsResponse) GetVariablesOk() (*[]BatchPutRecordsResponseVariables, bool) {
	if o == nil || o.Variables == nil {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *V4beta1BatchPutRecordsResponse) HasVariables() bool {
	if o != nil && o.Variables != nil {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []BatchPutRecordsResponseVariables and assigns it to the Variables field.
func (o *V4beta1BatchPutRecordsResponse) SetVariables(v []BatchPutRecordsResponseVariables) {
	o.Variables = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V4beta1BatchPutRecordsResponse) GetErrors() []V4beta1BatchPutRecordsResponseError {
	if o == nil || o.Errors == nil {
		var ret []V4beta1BatchPutRecordsResponseError
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1BatchPutRecordsResponse) GetErrorsOk() (*[]V4beta1BatchPutRecordsResponseError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V4beta1BatchPutRecordsResponse) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V4beta1BatchPutRecordsResponseError and assigns it to the Errors field.
func (o *V4beta1BatchPutRecordsResponse) SetErrors(v []V4beta1BatchPutRecordsResponseError) {
	o.Errors = &v
}

func (o V4beta1BatchPutRecordsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Keys != nil {
		toSerialize["keys"] = o.Keys
	}
	if o.Variables != nil {
		toSerialize["variables"] = o.Variables
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	return json.Marshal(toSerialize)
}

type NullableV4beta1BatchPutRecordsResponse struct {
	value *V4beta1BatchPutRecordsResponse
	isSet bool
}

func (v NullableV4beta1BatchPutRecordsResponse) Get() *V4beta1BatchPutRecordsResponse {
	return v.value
}

func (v *NullableV4beta1BatchPutRecordsResponse) Set(val *V4beta1BatchPutRecordsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV4beta1BatchPutRecordsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV4beta1BatchPutRecordsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4beta1BatchPutRecordsResponse(val *V4beta1BatchPutRecordsResponse) *NullableV4beta1BatchPutRecordsResponse {
	return &NullableV4beta1BatchPutRecordsResponse{value: val, isSet: true}
}

func (v NullableV4beta1BatchPutRecordsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4beta1BatchPutRecordsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
