/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ListPipelinesRequestView  - VIEW_UNSPECIFIED: The default / unset value. The API defaults to the `BASIC` view.  - BASIC: Include basic information including type, name, version and description but not the full step configuration. This is the default value (for both [ListPipelines](/docs/api-reference#operation/ListPipelines) and [GetPipeline](/docs/api-reference#operation/GetPipeline)).  - FULL: Include the information from `BASIC`, plus full step configuration.
type ListPipelinesRequestView string

// List of ListPipelinesRequestView
const (
	LISTPIPELINESREQUESTVIEW_VIEW_UNSPECIFIED ListPipelinesRequestView = "VIEW_UNSPECIFIED"
	LISTPIPELINESREQUESTVIEW_BASIC            ListPipelinesRequestView = "BASIC"
	LISTPIPELINESREQUESTVIEW_FULL             ListPipelinesRequestView = "FULL"
)

func (v *ListPipelinesRequestView) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ListPipelinesRequestView(value)
	for _, existing := range []ListPipelinesRequestView{"VIEW_UNSPECIFIED", "BASIC", "FULL"} {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ListPipelinesRequestView", value)
}

// Ptr returns reference to ListPipelinesRequestView value
func (v ListPipelinesRequestView) Ptr() *ListPipelinesRequestView {
	return &v
}

type NullableListPipelinesRequestView struct {
	value *ListPipelinesRequestView
	isSet bool
}

func (v NullableListPipelinesRequestView) Get() *ListPipelinesRequestView {
	return v.value
}

func (v *NullableListPipelinesRequestView) Set(val *ListPipelinesRequestView) {
	v.value = val
	v.isSet = true
}

func (v NullableListPipelinesRequestView) IsSet() bool {
	return v.isSet
}

func (v *NullableListPipelinesRequestView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPipelinesRequestView(val *ListPipelinesRequestView) *NullableListPipelinesRequestView {
	return &NullableListPipelinesRequestView{value: val, isSet: true}
}

func (v NullableListPipelinesRequestView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPipelinesRequestView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
