/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V4beta1SetDefaultPipelineRequest struct for V4beta1SetDefaultPipelineRequest
type V4beta1SetDefaultPipelineRequest struct {
	Type V4beta1PipelineType `json:"type"`
	// The name of the pipeline to use when not otherwise specified.
	Pipeline string `json:"pipeline"`
}

// NewV4beta1SetDefaultPipelineRequest instantiates a new V4beta1SetDefaultPipelineRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4beta1SetDefaultPipelineRequest(type_ V4beta1PipelineType, pipeline string) *V4beta1SetDefaultPipelineRequest {
	this := V4beta1SetDefaultPipelineRequest{}
	this.Type = type_
	this.Pipeline = pipeline
	return &this
}

// NewV4beta1SetDefaultPipelineRequestWithDefaults instantiates a new V4beta1SetDefaultPipelineRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4beta1SetDefaultPipelineRequestWithDefaults() *V4beta1SetDefaultPipelineRequest {
	this := V4beta1SetDefaultPipelineRequest{}
	var type_ V4beta1PipelineType = "TYPE_UNSPECIFIED"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *V4beta1SetDefaultPipelineRequest) GetType() V4beta1PipelineType {
	if o == nil {
		var ret V4beta1PipelineType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *V4beta1SetDefaultPipelineRequest) GetTypeOk() (*V4beta1PipelineType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *V4beta1SetDefaultPipelineRequest) SetType(v V4beta1PipelineType) {
	o.Type = v
}

// GetPipeline returns the Pipeline field value
func (o *V4beta1SetDefaultPipelineRequest) GetPipeline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pipeline
}

// GetPipelineOk returns a tuple with the Pipeline field value
// and a boolean to check if the value has been set.
func (o *V4beta1SetDefaultPipelineRequest) GetPipelineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pipeline, true
}

// SetPipeline sets field value
func (o *V4beta1SetDefaultPipelineRequest) SetPipeline(v string) {
	o.Pipeline = v
}

func (o V4beta1SetDefaultPipelineRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["pipeline"] = o.Pipeline
	}
	return json.Marshal(toSerialize)
}

type NullableV4beta1SetDefaultPipelineRequest struct {
	value *V4beta1SetDefaultPipelineRequest
	isSet bool
}

func (v NullableV4beta1SetDefaultPipelineRequest) Get() *V4beta1SetDefaultPipelineRequest {
	return v.value
}

func (v *NullableV4beta1SetDefaultPipelineRequest) Set(val *V4beta1SetDefaultPipelineRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV4beta1SetDefaultPipelineRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV4beta1SetDefaultPipelineRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4beta1SetDefaultPipelineRequest(val *V4beta1SetDefaultPipelineRequest) *NullableV4beta1SetDefaultPipelineRequest {
	return &NullableV4beta1SetDefaultPipelineRequest{value: val, isSet: true}
}

func (v NullableV4beta1SetDefaultPipelineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4beta1SetDefaultPipelineRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
