/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V4beta1GeneratePipelinesResponse struct for V4beta1GeneratePipelinesResponse
type V4beta1GeneratePipelinesResponse struct {
	RecordPipeline       *Sajariv4beta1Pipeline `json:"record_pipeline,omitempty"`
	QueryPipeline        *Sajariv4beta1Pipeline `json:"query_pipeline,omitempty"`
	AutocompletePipeline *Sajariv4beta1Pipeline `json:"autocomplete_pipeline,omitempty"`
}

// NewV4beta1GeneratePipelinesResponse instantiates a new V4beta1GeneratePipelinesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4beta1GeneratePipelinesResponse() *V4beta1GeneratePipelinesResponse {
	this := V4beta1GeneratePipelinesResponse{}
	return &this
}

// NewV4beta1GeneratePipelinesResponseWithDefaults instantiates a new V4beta1GeneratePipelinesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4beta1GeneratePipelinesResponseWithDefaults() *V4beta1GeneratePipelinesResponse {
	this := V4beta1GeneratePipelinesResponse{}
	return &this
}

// GetRecordPipeline returns the RecordPipeline field value if set, zero value otherwise.
func (o *V4beta1GeneratePipelinesResponse) GetRecordPipeline() Sajariv4beta1Pipeline {
	if o == nil || o.RecordPipeline == nil {
		var ret Sajariv4beta1Pipeline
		return ret
	}
	return *o.RecordPipeline
}

// GetRecordPipelineOk returns a tuple with the RecordPipeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1GeneratePipelinesResponse) GetRecordPipelineOk() (*Sajariv4beta1Pipeline, bool) {
	if o == nil || o.RecordPipeline == nil {
		return nil, false
	}
	return o.RecordPipeline, true
}

// HasRecordPipeline returns a boolean if a field has been set.
func (o *V4beta1GeneratePipelinesResponse) HasRecordPipeline() bool {
	if o != nil && o.RecordPipeline != nil {
		return true
	}

	return false
}

// SetRecordPipeline gets a reference to the given Sajariv4beta1Pipeline and assigns it to the RecordPipeline field.
func (o *V4beta1GeneratePipelinesResponse) SetRecordPipeline(v Sajariv4beta1Pipeline) {
	o.RecordPipeline = &v
}

// GetQueryPipeline returns the QueryPipeline field value if set, zero value otherwise.
func (o *V4beta1GeneratePipelinesResponse) GetQueryPipeline() Sajariv4beta1Pipeline {
	if o == nil || o.QueryPipeline == nil {
		var ret Sajariv4beta1Pipeline
		return ret
	}
	return *o.QueryPipeline
}

// GetQueryPipelineOk returns a tuple with the QueryPipeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1GeneratePipelinesResponse) GetQueryPipelineOk() (*Sajariv4beta1Pipeline, bool) {
	if o == nil || o.QueryPipeline == nil {
		return nil, false
	}
	return o.QueryPipeline, true
}

// HasQueryPipeline returns a boolean if a field has been set.
func (o *V4beta1GeneratePipelinesResponse) HasQueryPipeline() bool {
	if o != nil && o.QueryPipeline != nil {
		return true
	}

	return false
}

// SetQueryPipeline gets a reference to the given Sajariv4beta1Pipeline and assigns it to the QueryPipeline field.
func (o *V4beta1GeneratePipelinesResponse) SetQueryPipeline(v Sajariv4beta1Pipeline) {
	o.QueryPipeline = &v
}

// GetAutocompletePipeline returns the AutocompletePipeline field value if set, zero value otherwise.
func (o *V4beta1GeneratePipelinesResponse) GetAutocompletePipeline() Sajariv4beta1Pipeline {
	if o == nil || o.AutocompletePipeline == nil {
		var ret Sajariv4beta1Pipeline
		return ret
	}
	return *o.AutocompletePipeline
}

// GetAutocompletePipelineOk returns a tuple with the AutocompletePipeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1GeneratePipelinesResponse) GetAutocompletePipelineOk() (*Sajariv4beta1Pipeline, bool) {
	if o == nil || o.AutocompletePipeline == nil {
		return nil, false
	}
	return o.AutocompletePipeline, true
}

// HasAutocompletePipeline returns a boolean if a field has been set.
func (o *V4beta1GeneratePipelinesResponse) HasAutocompletePipeline() bool {
	if o != nil && o.AutocompletePipeline != nil {
		return true
	}

	return false
}

// SetAutocompletePipeline gets a reference to the given Sajariv4beta1Pipeline and assigns it to the AutocompletePipeline field.
func (o *V4beta1GeneratePipelinesResponse) SetAutocompletePipeline(v Sajariv4beta1Pipeline) {
	o.AutocompletePipeline = &v
}

func (o V4beta1GeneratePipelinesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RecordPipeline != nil {
		toSerialize["record_pipeline"] = o.RecordPipeline
	}
	if o.QueryPipeline != nil {
		toSerialize["query_pipeline"] = o.QueryPipeline
	}
	if o.AutocompletePipeline != nil {
		toSerialize["autocomplete_pipeline"] = o.AutocompletePipeline
	}
	return json.Marshal(toSerialize)
}

type NullableV4beta1GeneratePipelinesResponse struct {
	value *V4beta1GeneratePipelinesResponse
	isSet bool
}

func (v NullableV4beta1GeneratePipelinesResponse) Get() *V4beta1GeneratePipelinesResponse {
	return v.value
}

func (v *NullableV4beta1GeneratePipelinesResponse) Set(val *V4beta1GeneratePipelinesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV4beta1GeneratePipelinesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV4beta1GeneratePipelinesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4beta1GeneratePipelinesResponse(val *V4beta1GeneratePipelinesResponse) *NullableV4beta1GeneratePipelinesResponse {
	return &NullableV4beta1GeneratePipelinesResponse{value: val, isSet: true}
}

func (v NullableV4beta1GeneratePipelinesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4beta1GeneratePipelinesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
