/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// V4beta1ListPipelinesRequestView  - VIEW_UNSPECIFIED: The default / unset value. The API defaults to the `BASIC` view.  - BASIC: Include basic information including type, name, version and description but not the full step configuration. This is the default value (for both [ListPipelines](/docs/api-reference#operation/ListPipelines) and [GetPipeline](/docs/api-reference#operation/GetPipeline)).  - FULL: Include the information from `BASIC`, plus full step configuration.
type V4beta1ListPipelinesRequestView string

// List of v4beta1ListPipelinesRequestView
const (
	V4BETA1LISTPIPELINESREQUESTVIEW_VIEW_UNSPECIFIED V4beta1ListPipelinesRequestView = "VIEW_UNSPECIFIED"
	V4BETA1LISTPIPELINESREQUESTVIEW_BASIC            V4beta1ListPipelinesRequestView = "BASIC"
	V4BETA1LISTPIPELINESREQUESTVIEW_FULL             V4beta1ListPipelinesRequestView = "FULL"
)

func (v *V4beta1ListPipelinesRequestView) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V4beta1ListPipelinesRequestView(value)
	for _, existing := range []V4beta1ListPipelinesRequestView{"VIEW_UNSPECIFIED", "BASIC", "FULL"} {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V4beta1ListPipelinesRequestView", value)
}

// Ptr returns reference to v4beta1ListPipelinesRequestView value
func (v V4beta1ListPipelinesRequestView) Ptr() *V4beta1ListPipelinesRequestView {
	return &v
}

type NullableV4beta1ListPipelinesRequestView struct {
	value *V4beta1ListPipelinesRequestView
	isSet bool
}

func (v NullableV4beta1ListPipelinesRequestView) Get() *V4beta1ListPipelinesRequestView {
	return v.value
}

func (v *NullableV4beta1ListPipelinesRequestView) Set(val *V4beta1ListPipelinesRequestView) {
	v.value = val
	v.isSet = true
}

func (v NullableV4beta1ListPipelinesRequestView) IsSet() bool {
	return v.isSet
}

func (v *NullableV4beta1ListPipelinesRequestView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4beta1ListPipelinesRequestView(val *V4beta1ListPipelinesRequestView) *NullableV4beta1ListPipelinesRequestView {
	return &NullableV4beta1ListPipelinesRequestView{value: val, isSet: true}
}

func (v NullableV4beta1ListPipelinesRequestView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4beta1ListPipelinesRequestView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
