/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V4beta1BatchUpsertRecordsResponseError struct for V4beta1BatchUpsertRecordsResponseError
type V4beta1BatchUpsertRecordsResponseError struct {
	// Index of the record in `records` that this error corresponds to.
	Index  *int32      `json:"index,omitempty"`
	Status *RpcStatus1 `json:"status,omitempty"`
}

// NewV4beta1BatchUpsertRecordsResponseError instantiates a new V4beta1BatchUpsertRecordsResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4beta1BatchUpsertRecordsResponseError() *V4beta1BatchUpsertRecordsResponseError {
	this := V4beta1BatchUpsertRecordsResponseError{}
	return &this
}

// NewV4beta1BatchUpsertRecordsResponseErrorWithDefaults instantiates a new V4beta1BatchUpsertRecordsResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4beta1BatchUpsertRecordsResponseErrorWithDefaults() *V4beta1BatchUpsertRecordsResponseError {
	this := V4beta1BatchUpsertRecordsResponseError{}
	return &this
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *V4beta1BatchUpsertRecordsResponseError) GetIndex() int32 {
	if o == nil || o.Index == nil {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1BatchUpsertRecordsResponseError) GetIndexOk() (*int32, bool) {
	if o == nil || o.Index == nil {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *V4beta1BatchUpsertRecordsResponseError) HasIndex() bool {
	if o != nil && o.Index != nil {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *V4beta1BatchUpsertRecordsResponseError) SetIndex(v int32) {
	o.Index = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V4beta1BatchUpsertRecordsResponseError) GetStatus() RpcStatus1 {
	if o == nil || o.Status == nil {
		var ret RpcStatus1
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1BatchUpsertRecordsResponseError) GetStatusOk() (*RpcStatus1, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V4beta1BatchUpsertRecordsResponseError) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RpcStatus1 and assigns it to the Status field.
func (o *V4beta1BatchUpsertRecordsResponseError) SetStatus(v RpcStatus1) {
	o.Status = &v
}

func (o V4beta1BatchUpsertRecordsResponseError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Index != nil {
		toSerialize["index"] = o.Index
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableV4beta1BatchUpsertRecordsResponseError struct {
	value *V4beta1BatchUpsertRecordsResponseError
	isSet bool
}

func (v NullableV4beta1BatchUpsertRecordsResponseError) Get() *V4beta1BatchUpsertRecordsResponseError {
	return v.value
}

func (v *NullableV4beta1BatchUpsertRecordsResponseError) Set(val *V4beta1BatchUpsertRecordsResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableV4beta1BatchUpsertRecordsResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableV4beta1BatchUpsertRecordsResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4beta1BatchUpsertRecordsResponseError(val *V4beta1BatchUpsertRecordsResponseError) *NullableV4beta1BatchUpsertRecordsResponseError {
	return &NullableV4beta1BatchUpsertRecordsResponseError{value: val, isSet: true}
}

func (v NullableV4beta1BatchUpsertRecordsResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4beta1BatchUpsertRecordsResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
