/*
 * Search.io API
 *
 * Search.io is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4
 * Contact: support@search.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PipelineStep Step creates a pipeline step.
type PipelineStep struct {
	// Annotations added to the request when the step is run.
	Annotations *[]string `json:"annotations,omitempty"`
	// A condition expression to determine if the step should be run.  This is a filter expression much like the query filter expression, but it acts upon the pipeline variables.  For example, to only run the step if the pipeline `q` variable is not empty, set this to `q != ''`.
	Condition *string `json:"condition,omitempty"`
	// Description for the step. Overrides the default description.
	Description *string `json:"description,omitempty"`
	// ID of the step template.
	Id string `json:"id"`
	// Bindings for the step parameters.
	Params *map[string]PipelineStepParamBinding `json:"params,omitempty"`
	// Title for the step. Overrides the default title.
	Title *string `json:"title,omitempty"`
}

// NewPipelineStep instantiates a new PipelineStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineStep(id string) *PipelineStep {
	this := PipelineStep{}
	this.Id = id
	return &this
}

// NewPipelineStepWithDefaults instantiates a new PipelineStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineStepWithDefaults() *PipelineStep {
	this := PipelineStep{}
	return &this
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *PipelineStep) GetAnnotations() []string {
	if o == nil || o.Annotations == nil {
		var ret []string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetAnnotationsOk() (*[]string, bool) {
	if o == nil || o.Annotations == nil {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *PipelineStep) HasAnnotations() bool {
	if o != nil && o.Annotations != nil {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given []string and assigns it to the Annotations field.
func (o *PipelineStep) SetAnnotations(v []string) {
	o.Annotations = &v
}

// GetCondition returns the Condition field value if set, zero value otherwise.
func (o *PipelineStep) GetCondition() string {
	if o == nil || o.Condition == nil {
		var ret string
		return ret
	}
	return *o.Condition
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetConditionOk() (*string, bool) {
	if o == nil || o.Condition == nil {
		return nil, false
	}
	return o.Condition, true
}

// HasCondition returns a boolean if a field has been set.
func (o *PipelineStep) HasCondition() bool {
	if o != nil && o.Condition != nil {
		return true
	}

	return false
}

// SetCondition gets a reference to the given string and assigns it to the Condition field.
func (o *PipelineStep) SetCondition(v string) {
	o.Condition = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PipelineStep) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PipelineStep) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PipelineStep) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value
func (o *PipelineStep) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PipelineStep) SetId(v string) {
	o.Id = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *PipelineStep) GetParams() map[string]PipelineStepParamBinding {
	if o == nil || o.Params == nil {
		var ret map[string]PipelineStepParamBinding
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetParamsOk() (*map[string]PipelineStepParamBinding, bool) {
	if o == nil || o.Params == nil {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *PipelineStep) HasParams() bool {
	if o != nil && o.Params != nil {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]PipelineStepParamBinding and assigns it to the Params field.
func (o *PipelineStep) SetParams(v map[string]PipelineStepParamBinding) {
	o.Params = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *PipelineStep) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *PipelineStep) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *PipelineStep) SetTitle(v string) {
	o.Title = &v
}

func (o PipelineStep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Annotations != nil {
		toSerialize["annotations"] = o.Annotations
	}
	if o.Condition != nil {
		toSerialize["condition"] = o.Condition
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Params != nil {
		toSerialize["params"] = o.Params
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	return json.Marshal(toSerialize)
}

type NullablePipelineStep struct {
	value *PipelineStep
	isSet bool
}

func (v NullablePipelineStep) Get() *PipelineStep {
	return v.value
}

func (v *NullablePipelineStep) Set(val *PipelineStep) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineStep) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineStep(val *PipelineStep) *NullablePipelineStep {
	return &NullablePipelineStep{value: val, isSet: true}
}

func (v NullablePipelineStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
