/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GatewayruntimeError1 struct for GatewayruntimeError1
type GatewayruntimeError1 struct {
	Error   *string        `json:"error,omitempty"`
	Code    *int32         `json:"code,omitempty"`
	Message *string        `json:"message,omitempty"`
	Details *[]ProtobufAny `json:"details,omitempty"`
}

// NewGatewayruntimeError1 instantiates a new GatewayruntimeError1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayruntimeError1() *GatewayruntimeError1 {
	this := GatewayruntimeError1{}
	return &this
}

// NewGatewayruntimeError1WithDefaults instantiates a new GatewayruntimeError1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayruntimeError1WithDefaults() *GatewayruntimeError1 {
	this := GatewayruntimeError1{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GatewayruntimeError1) GetError() string {
	if o == nil || o.Error == nil {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayruntimeError1) GetErrorOk() (*string, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GatewayruntimeError1) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GatewayruntimeError1) SetError(v string) {
	o.Error = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GatewayruntimeError1) GetCode() int32 {
	if o == nil || o.Code == nil {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayruntimeError1) GetCodeOk() (*int32, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GatewayruntimeError1) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *GatewayruntimeError1) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GatewayruntimeError1) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayruntimeError1) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GatewayruntimeError1) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GatewayruntimeError1) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *GatewayruntimeError1) GetDetails() []ProtobufAny {
	if o == nil || o.Details == nil {
		var ret []ProtobufAny
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayruntimeError1) GetDetailsOk() (*[]ProtobufAny, bool) {
	if o == nil || o.Details == nil {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *GatewayruntimeError1) HasDetails() bool {
	if o != nil && o.Details != nil {
		return true
	}

	return false
}

// SetDetails gets a reference to the given []ProtobufAny and assigns it to the Details field.
func (o *GatewayruntimeError1) SetDetails(v []ProtobufAny) {
	o.Details = &v
}

func (o GatewayruntimeError1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Details != nil {
		toSerialize["details"] = o.Details
	}
	return json.Marshal(toSerialize)
}

type NullableGatewayruntimeError1 struct {
	value *GatewayruntimeError1
	isSet bool
}

func (v NullableGatewayruntimeError1) Get() *GatewayruntimeError1 {
	return v.value
}

func (v *NullableGatewayruntimeError1) Set(val *GatewayruntimeError1) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayruntimeError1) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayruntimeError1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayruntimeError1(val *GatewayruntimeError1) *NullableGatewayruntimeError1 {
	return &NullableGatewayruntimeError1{value: val, isSet: true}
}

func (v NullableGatewayruntimeError1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayruntimeError1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
