/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DeleteRecordRequest struct for DeleteRecordRequest
type DeleteRecordRequest struct {
	Key RecordKey `json:"key"`
}

// NewDeleteRecordRequest instantiates a new DeleteRecordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteRecordRequest(key RecordKey) *DeleteRecordRequest {
	this := DeleteRecordRequest{}
	this.Key = key
	return &this
}

// NewDeleteRecordRequestWithDefaults instantiates a new DeleteRecordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteRecordRequestWithDefaults() *DeleteRecordRequest {
	this := DeleteRecordRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *DeleteRecordRequest) GetKey() RecordKey {
	if o == nil {
		var ret RecordKey
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *DeleteRecordRequest) GetKeyOk() (*RecordKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *DeleteRecordRequest) SetKey(v RecordKey) {
	o.Key = v
}

func (o DeleteRecordRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["key"] = o.Key
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteRecordRequest struct {
	value *DeleteRecordRequest
	isSet bool
}

func (v NullableDeleteRecordRequest) Get() *DeleteRecordRequest {
	return v.value
}

func (v *NullableDeleteRecordRequest) Set(val *DeleteRecordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteRecordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteRecordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteRecordRequest(val *DeleteRecordRequest) *NullableDeleteRecordRequest {
	return &NullableDeleteRecordRequest{value: val, isSet: true}
}

func (v NullableDeleteRecordRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteRecordRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
