/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V4beta1ListCollectionsResponse struct for V4beta1ListCollectionsResponse
type V4beta1ListCollectionsResponse struct {
	// The collections from the specified account.
	Collections *[]V4beta1Collection `json:"collections,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.  If this field is omitted, there are no subsequent pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// NewV4beta1ListCollectionsResponse instantiates a new V4beta1ListCollectionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4beta1ListCollectionsResponse() *V4beta1ListCollectionsResponse {
	this := V4beta1ListCollectionsResponse{}
	return &this
}

// NewV4beta1ListCollectionsResponseWithDefaults instantiates a new V4beta1ListCollectionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4beta1ListCollectionsResponseWithDefaults() *V4beta1ListCollectionsResponse {
	this := V4beta1ListCollectionsResponse{}
	return &this
}

// GetCollections returns the Collections field value if set, zero value otherwise.
func (o *V4beta1ListCollectionsResponse) GetCollections() []V4beta1Collection {
	if o == nil || o.Collections == nil {
		var ret []V4beta1Collection
		return ret
	}
	return *o.Collections
}

// GetCollectionsOk returns a tuple with the Collections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1ListCollectionsResponse) GetCollectionsOk() (*[]V4beta1Collection, bool) {
	if o == nil || o.Collections == nil {
		return nil, false
	}
	return o.Collections, true
}

// HasCollections returns a boolean if a field has been set.
func (o *V4beta1ListCollectionsResponse) HasCollections() bool {
	if o != nil && o.Collections != nil {
		return true
	}

	return false
}

// SetCollections gets a reference to the given []V4beta1Collection and assigns it to the Collections field.
func (o *V4beta1ListCollectionsResponse) SetCollections(v []V4beta1Collection) {
	o.Collections = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *V4beta1ListCollectionsResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1ListCollectionsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || o.NextPageToken == nil {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *V4beta1ListCollectionsResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *V4beta1ListCollectionsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o V4beta1ListCollectionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Collections != nil {
		toSerialize["collections"] = o.Collections
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}

type NullableV4beta1ListCollectionsResponse struct {
	value *V4beta1ListCollectionsResponse
	isSet bool
}

func (v NullableV4beta1ListCollectionsResponse) Get() *V4beta1ListCollectionsResponse {
	return v.value
}

func (v *NullableV4beta1ListCollectionsResponse) Set(val *V4beta1ListCollectionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV4beta1ListCollectionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV4beta1ListCollectionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4beta1ListCollectionsResponse(val *V4beta1ListCollectionsResponse) *NullableV4beta1ListCollectionsResponse {
	return &NullableV4beta1ListCollectionsResponse{value: val, isSet: true}
}

func (v NullableV4beta1ListCollectionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4beta1ListCollectionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
