/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Sajariv4beta1Key struct for Sajariv4beta1Key
type Sajariv4beta1Key struct {
	// A field in your record that uniquely identifies it, e.g. `id`.
	Field string `json:"field"`
	// The value of `field` in your record, e.g. `b217a995-597c-410f-bef2-60e9f8c0aadd`.
	Value string `json:"value"`
}

// NewSajariv4beta1Key instantiates a new Sajariv4beta1Key object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSajariv4beta1Key(field string, value string) *Sajariv4beta1Key {
	this := Sajariv4beta1Key{}
	this.Field = field
	this.Value = value
	return &this
}

// NewSajariv4beta1KeyWithDefaults instantiates a new Sajariv4beta1Key object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSajariv4beta1KeyWithDefaults() *Sajariv4beta1Key {
	this := Sajariv4beta1Key{}
	return &this
}

// GetField returns the Field field value
func (o *Sajariv4beta1Key) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *Sajariv4beta1Key) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *Sajariv4beta1Key) SetField(v string) {
	o.Field = v
}

// GetValue returns the Value field value
func (o *Sajariv4beta1Key) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Sajariv4beta1Key) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Sajariv4beta1Key) SetValue(v string) {
	o.Value = v
}

func (o Sajariv4beta1Key) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["field"] = o.Field
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableSajariv4beta1Key struct {
	value *Sajariv4beta1Key
	isSet bool
}

func (v NullableSajariv4beta1Key) Get() *Sajariv4beta1Key {
	return v.value
}

func (v *NullableSajariv4beta1Key) Set(val *Sajariv4beta1Key) {
	v.value = val
	v.isSet = true
}

func (v NullableSajariv4beta1Key) IsSet() bool {
	return v.isSet
}

func (v *NullableSajariv4beta1Key) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSajariv4beta1Key(val *Sajariv4beta1Key) *NullableSajariv4beta1Key {
	return &NullableSajariv4beta1Key{value: val, isSet: true}
}

func (v NullableSajariv4beta1Key) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSajariv4beta1Key) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
