/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V4beta1PutRecordRequest struct for V4beta1PutRecordRequest
type V4beta1PutRecordRequest struct {
	Pipeline *V4beta1PutRecordRequestPipeline `json:"pipeline,omitempty"`
	// An object made up of field-value pairs that contains the record data.
	Record map[string]interface{} `json:"record"`
	// The initial values for the variables the pipeline operates on and transforms throughout its steps.
	Variables *map[string]interface{} `json:"variables,omitempty"`
}

// NewV4beta1PutRecordRequest instantiates a new V4beta1PutRecordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4beta1PutRecordRequest(record map[string]interface{}) *V4beta1PutRecordRequest {
	this := V4beta1PutRecordRequest{}
	this.Record = record
	return &this
}

// NewV4beta1PutRecordRequestWithDefaults instantiates a new V4beta1PutRecordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4beta1PutRecordRequestWithDefaults() *V4beta1PutRecordRequest {
	this := V4beta1PutRecordRequest{}
	return &this
}

// GetPipeline returns the Pipeline field value if set, zero value otherwise.
func (o *V4beta1PutRecordRequest) GetPipeline() V4beta1PutRecordRequestPipeline {
	if o == nil || o.Pipeline == nil {
		var ret V4beta1PutRecordRequestPipeline
		return ret
	}
	return *o.Pipeline
}

// GetPipelineOk returns a tuple with the Pipeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1PutRecordRequest) GetPipelineOk() (*V4beta1PutRecordRequestPipeline, bool) {
	if o == nil || o.Pipeline == nil {
		return nil, false
	}
	return o.Pipeline, true
}

// HasPipeline returns a boolean if a field has been set.
func (o *V4beta1PutRecordRequest) HasPipeline() bool {
	if o != nil && o.Pipeline != nil {
		return true
	}

	return false
}

// SetPipeline gets a reference to the given V4beta1PutRecordRequestPipeline and assigns it to the Pipeline field.
func (o *V4beta1PutRecordRequest) SetPipeline(v V4beta1PutRecordRequestPipeline) {
	o.Pipeline = &v
}

// GetRecord returns the Record field value
func (o *V4beta1PutRecordRequest) GetRecord() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Record
}

// GetRecordOk returns a tuple with the Record field value
// and a boolean to check if the value has been set.
func (o *V4beta1PutRecordRequest) GetRecordOk() (*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Record, true
}

// SetRecord sets field value
func (o *V4beta1PutRecordRequest) SetRecord(v map[string]interface{}) {
	o.Record = v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *V4beta1PutRecordRequest) GetVariables() map[string]interface{} {
	if o == nil || o.Variables == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1PutRecordRequest) GetVariablesOk() (*map[string]interface{}, bool) {
	if o == nil || o.Variables == nil {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *V4beta1PutRecordRequest) HasVariables() bool {
	if o != nil && o.Variables != nil {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]interface{} and assigns it to the Variables field.
func (o *V4beta1PutRecordRequest) SetVariables(v map[string]interface{}) {
	o.Variables = &v
}

func (o V4beta1PutRecordRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pipeline != nil {
		toSerialize["pipeline"] = o.Pipeline
	}
	if true {
		toSerialize["record"] = o.Record
	}
	if o.Variables != nil {
		toSerialize["variables"] = o.Variables
	}
	return json.Marshal(toSerialize)
}

type NullableV4beta1PutRecordRequest struct {
	value *V4beta1PutRecordRequest
	isSet bool
}

func (v NullableV4beta1PutRecordRequest) Get() *V4beta1PutRecordRequest {
	return v.value
}

func (v *NullableV4beta1PutRecordRequest) Set(val *V4beta1PutRecordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV4beta1PutRecordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV4beta1PutRecordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4beta1PutRecordRequest(val *V4beta1PutRecordRequest) *NullableV4beta1PutRecordRequest {
	return &NullableV4beta1PutRecordRequest{value: val, isSet: true}
}

func (v NullableV4beta1PutRecordRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4beta1PutRecordRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
