/*
 * Search.io API
 *
 * Search.io is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4
 * Contact: support@search.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListPromotionsResponse struct for ListPromotionsResponse
type ListPromotionsResponse struct {
	// A token, which can be sent as `page_token` to retrieve the next page.  If this field is omitted, there are no subsequent pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
	// The promotions.
	Promotions *[]Promotion `json:"promotions,omitempty"`
}

// NewListPromotionsResponse instantiates a new ListPromotionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPromotionsResponse() *ListPromotionsResponse {
	this := ListPromotionsResponse{}
	return &this
}

// NewListPromotionsResponseWithDefaults instantiates a new ListPromotionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPromotionsResponseWithDefaults() *ListPromotionsResponse {
	this := ListPromotionsResponse{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListPromotionsResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPromotionsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || o.NextPageToken == nil {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListPromotionsResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListPromotionsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetPromotions returns the Promotions field value if set, zero value otherwise.
func (o *ListPromotionsResponse) GetPromotions() []Promotion {
	if o == nil || o.Promotions == nil {
		var ret []Promotion
		return ret
	}
	return *o.Promotions
}

// GetPromotionsOk returns a tuple with the Promotions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPromotionsResponse) GetPromotionsOk() (*[]Promotion, bool) {
	if o == nil || o.Promotions == nil {
		return nil, false
	}
	return o.Promotions, true
}

// HasPromotions returns a boolean if a field has been set.
func (o *ListPromotionsResponse) HasPromotions() bool {
	if o != nil && o.Promotions != nil {
		return true
	}

	return false
}

// SetPromotions gets a reference to the given []Promotion and assigns it to the Promotions field.
func (o *ListPromotionsResponse) SetPromotions(v []Promotion) {
	o.Promotions = &v
}

func (o ListPromotionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	if o.Promotions != nil {
		toSerialize["promotions"] = o.Promotions
	}
	return json.Marshal(toSerialize)
}

type NullableListPromotionsResponse struct {
	value *ListPromotionsResponse
	isSet bool
}

func (v NullableListPromotionsResponse) Get() *ListPromotionsResponse {
	return v.value
}

func (v *NullableListPromotionsResponse) Set(val *ListPromotionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListPromotionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListPromotionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPromotionsResponse(val *ListPromotionsResponse) *NullableListPromotionsResponse {
	return &NullableListPromotionsResponse{value: val, isSet: true}
}

func (v NullableListPromotionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPromotionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
