/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V4beta1ListPipelinesResponse struct for V4beta1ListPipelinesResponse
type V4beta1ListPipelinesResponse struct {
	// The pipelines from the specified collection.
	Pipelines *[]Sajariv4beta1Pipeline1 `json:"pipelines,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.  If this field is omitted, there are no subsequent pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// NewV4beta1ListPipelinesResponse instantiates a new V4beta1ListPipelinesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV4beta1ListPipelinesResponse() *V4beta1ListPipelinesResponse {
	this := V4beta1ListPipelinesResponse{}
	return &this
}

// NewV4beta1ListPipelinesResponseWithDefaults instantiates a new V4beta1ListPipelinesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV4beta1ListPipelinesResponseWithDefaults() *V4beta1ListPipelinesResponse {
	this := V4beta1ListPipelinesResponse{}
	return &this
}

// GetPipelines returns the Pipelines field value if set, zero value otherwise.
func (o *V4beta1ListPipelinesResponse) GetPipelines() []Sajariv4beta1Pipeline1 {
	if o == nil || o.Pipelines == nil {
		var ret []Sajariv4beta1Pipeline1
		return ret
	}
	return *o.Pipelines
}

// GetPipelinesOk returns a tuple with the Pipelines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1ListPipelinesResponse) GetPipelinesOk() (*[]Sajariv4beta1Pipeline1, bool) {
	if o == nil || o.Pipelines == nil {
		return nil, false
	}
	return o.Pipelines, true
}

// HasPipelines returns a boolean if a field has been set.
func (o *V4beta1ListPipelinesResponse) HasPipelines() bool {
	if o != nil && o.Pipelines != nil {
		return true
	}

	return false
}

// SetPipelines gets a reference to the given []Sajariv4beta1Pipeline1 and assigns it to the Pipelines field.
func (o *V4beta1ListPipelinesResponse) SetPipelines(v []Sajariv4beta1Pipeline1) {
	o.Pipelines = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *V4beta1ListPipelinesResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V4beta1ListPipelinesResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || o.NextPageToken == nil {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *V4beta1ListPipelinesResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *V4beta1ListPipelinesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o V4beta1ListPipelinesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pipelines != nil {
		toSerialize["pipelines"] = o.Pipelines
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}

type NullableV4beta1ListPipelinesResponse struct {
	value *V4beta1ListPipelinesResponse
	isSet bool
}

func (v NullableV4beta1ListPipelinesResponse) Get() *V4beta1ListPipelinesResponse {
	return v.value
}

func (v *NullableV4beta1ListPipelinesResponse) Set(val *V4beta1ListPipelinesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV4beta1ListPipelinesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV4beta1ListPipelinesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV4beta1ListPipelinesResponse(val *V4beta1ListPipelinesResponse) *NullableV4beta1ListPipelinesResponse {
	return &NullableV4beta1ListPipelinesResponse{value: val, isSet: true}
}

func (v NullableV4beta1ListPipelinesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV4beta1ListPipelinesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
