/*
 * Sajari API
 *
 * Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.
 *
 * API version: v4beta1
 * Contact: support@sajari.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TokenPosNeg PosNeg is a pair of tokens which are used to mark a record as a good/bad result for a SearchRequest.
type TokenPosNeg struct {
	Pos *string `json:"pos,omitempty"`
	Neg *string `json:"neg,omitempty"`
}

// NewTokenPosNeg instantiates a new TokenPosNeg object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenPosNeg() *TokenPosNeg {
	this := TokenPosNeg{}
	return &this
}

// NewTokenPosNegWithDefaults instantiates a new TokenPosNeg object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenPosNegWithDefaults() *TokenPosNeg {
	this := TokenPosNeg{}
	return &this
}

// GetPos returns the Pos field value if set, zero value otherwise.
func (o *TokenPosNeg) GetPos() string {
	if o == nil || o.Pos == nil {
		var ret string
		return ret
	}
	return *o.Pos
}

// GetPosOk returns a tuple with the Pos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenPosNeg) GetPosOk() (*string, bool) {
	if o == nil || o.Pos == nil {
		return nil, false
	}
	return o.Pos, true
}

// HasPos returns a boolean if a field has been set.
func (o *TokenPosNeg) HasPos() bool {
	if o != nil && o.Pos != nil {
		return true
	}

	return false
}

// SetPos gets a reference to the given string and assigns it to the Pos field.
func (o *TokenPosNeg) SetPos(v string) {
	o.Pos = &v
}

// GetNeg returns the Neg field value if set, zero value otherwise.
func (o *TokenPosNeg) GetNeg() string {
	if o == nil || o.Neg == nil {
		var ret string
		return ret
	}
	return *o.Neg
}

// GetNegOk returns a tuple with the Neg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenPosNeg) GetNegOk() (*string, bool) {
	if o == nil || o.Neg == nil {
		return nil, false
	}
	return o.Neg, true
}

// HasNeg returns a boolean if a field has been set.
func (o *TokenPosNeg) HasNeg() bool {
	if o != nil && o.Neg != nil {
		return true
	}

	return false
}

// SetNeg gets a reference to the given string and assigns it to the Neg field.
func (o *TokenPosNeg) SetNeg(v string) {
	o.Neg = &v
}

func (o TokenPosNeg) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pos != nil {
		toSerialize["pos"] = o.Pos
	}
	if o.Neg != nil {
		toSerialize["neg"] = o.Neg
	}
	return json.Marshal(toSerialize)
}

type NullableTokenPosNeg struct {
	value *TokenPosNeg
	isSet bool
}

func (v NullableTokenPosNeg) Get() *TokenPosNeg {
	return v.value
}

func (v *NullableTokenPosNeg) Set(val *TokenPosNeg) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenPosNeg) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenPosNeg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenPosNeg(val *TokenPosNeg) *NullableTokenPosNeg {
	return &NullableTokenPosNeg{value: val, isSet: true}
}

func (v NullableTokenPosNeg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenPosNeg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
